"""Phase 6 -- report: a migration report built only from facts the pipeline recorded."""
from __future__ import annotations

import importlib.util
import json
import os
from pathlib import Path

from . import apicases, decisions, gitutil
from .config import Config
from .testing import summarize_e2e
from .ui import ok, step


def _load(path: Path):
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else None


def backend_coverage(cfg: Config) -> dict | None:
    """Run the API parity cases in-process against modern/backend with coverage.py."""
    app_file = cfg.paths["modern_backend"] / "app.py"
    if not app_file.exists():
        return None
    import coverage

    os.environ["TEST_HOOKS"] = "1"
    cov = coverage.Coverage(data_file=None, include=[str(app_file)])
    cov.start()
    try:
        spec = importlib.util.spec_from_file_location("modern_backend_app", app_file)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)  # type: ignore[union-attr]
        send = apicases.flask_sender(module.app)
        for steps in apicases.load_cases(cfg.root / "parity" / "api" / "cases.yaml").values():
            apicases.run_case(send, steps)
    finally:
        cov.stop()
    _, statements, _, missing, _ = cov.analysis2(str(app_file))
    pct = 100.0 * (len(statements) - len(missing)) / max(len(statements), 1)
    return {"percent": round(pct, 1), "statements": len(statements), "missing": missing}


def _classify(commit: dict) -> str:
    subject = commit["subject"]
    if subject.startswith("ai:"):
        return "AI (Claude Code)"
    if subject.startswith("codemod:"):
        return "Codemod"
    if subject.startswith("modernize:"):
        return "Pipeline"
    return "Human"


def build_report(cfg: Config) -> Path:
    step("Report · what changed, what was proven, who decided")
    root = cfg.root
    plan = _load(cfg.out / "discover" / "plan.json")
    lock = _load(cfg.out / "lock.json")
    api = _load(cfg.out / "parity" / "modern" / "api-results.json")
    e2e = {t: summarize_e2e(cfg.out / "parity" / f"e2e-{t}.json", True) for t in ("legacy", "modern", "hybrid")}
    dec = decisions.load(cfg)
    commits = gitutil.log(root, "modern/")
    cov = backend_coverage(cfg)

    buckets: dict[str, list[int]] = {}
    commit_rows = []
    for c in commits:
        kind = _classify(c)
        files, added, removed = gitutil.numstat(root, c["sha"])
        b = buckets.setdefault(kind, [0, 0, 0])
        b[0] += 1
        b[1] += added
        b[2] += removed
        commit_rows.append(f"| `{c['sha']}` | {kind} | {c['subject']} | +{added} −{removed} |")

    review_left = []
    for path in (cfg.paths["modern_backend"], cfg.paths["modern_frontend"] / "src"):
        if path.exists():
            for f in path.rglob("*"):
                if f.is_file() and f.suffix in (".py", ".js", ".jsx"):
                    for i, line in enumerate(f.read_text(encoding="utf-8", errors="ignore").splitlines(), 1):
                        if "MODERNIZE-REVIEW" in line:
                            review_left.append(f"{f.relative_to(root).as_posix()}:{i}")

    L = [f"# Migration report: {cfg.project}", "", "Generated by `modernize report` from the pipeline's own records. Nothing here is written by an AI.", ""]

    L += ["## Result", ""]
    api_ok = bool(api) and not api.get("failed") and api.get("mode") == "compare"
    rows = [
        ("Backend: Python 2.7 → 3.12", api_ok,
         f"{len(api['passed'])} of {len(api['passed']) + len(api['failed'])} API cases match the legacy recording" if api else "not verified yet"),
    ]
    for t, label in (("modern", "Frontend: React 19 app"), ("hybrid", "Hybrid: React inside AngularJS")):
        s = e2e[t]
        total = s["passed"] + s["failed"]
        rows.append((label, total and not s["failed"], f"{s['passed']} of {total} browser tests pass" if total else "not verified yet"))
    L += ["| Part | Status | Evidence |", "|---|---|---|"]
    for label, good, evidence in rows:
        L.append(f"| {label} | {'✅ parity proven' if good else '⚠️ open'} | {evidence} |")
    L.append("")

    if lock:
        L += ["## The contract", "",
              f"Recorded from the running legacy app before any code changed: **{lock['api_cases']} API cases "
              f"({lock['api_requests']} requests)** and **{lock['browser_tests']} browser tests** "
              "(`parity/api/golden/`, `parity/e2e/tests/`).", ""]

    if plan:
        b = plan["backend"]
        L += ["## What discovery found", "",
              f"- Backend: {b['syntax']} syntax changes, {b['runtime']} runtime breaks, {b['semantic']} silent behaviour risks.",
              f"- Frontend: {len(plan['frontend']['units'])} AngularJS units, {plan['frontend']['semantic']} behaviours flagged to preserve.",
              "", "Full list: `migration/PLAN.md`.", ""]

    L += ["## Who changed what", "", "| Changed by | Commits | Lines added | Lines removed |", "|---|---|---|---|"]
    for kind in ("Codemod", "AI (Claude Code)", "Pipeline", "Human"):
        if kind in buckets:
            n, a, r = buckets[kind]
            L.append(f"| {kind} | {n} | {a} | {r} |")
    L += ["", "“Pipeline” = copies, scaffolding and accepted decisions. Every row below is one commit and can be undone with `git revert <sha>`.", "",
          "| Commit | By | What | Lines |", "|---|---|---|---|", *commit_rows, ""]

    ai_rows: dict[str, list[str]] = {}
    for c in commits:
        if c["subject"].startswith("ai:"):
            unit, _, rest = c["subject"][3:].strip().partition(" attempt ")
            ai_rows.setdefault(unit, []).append(rest)
    usage_file = cfg.out / "ai-usage.jsonl"
    session_cost: dict[str, float] = {}
    if usage_file.exists():
        for line in usage_file.read_text(encoding="utf-8").splitlines():
            row = json.loads(line)
            if row.get("session") and row.get("cost_usd") is not None:
                # A resumed session reports its running total, so keep the largest value per session.
                session_cost[row["session"]] = max(session_cost.get(row["session"], 0.0), float(row["cost_usd"]))
    if ai_rows:
        L += ["## AI steps (Claude Code)", "",
              f"Each step had at most {cfg.max_attempts} attempts and a ${cfg.budget_usd:.2f} spend cap per attempt; "
              "after every attempt the pipeline ran the step's check.", "",
              "| Step | Attempts | Result |", "|---|---|---|"]
        for unit, attempts in ai_rows.items():
            last = attempts[-1]
            L.append(f"| {unit} | {len(attempts)} | {'check passes' if 'passes' in last else 'check fails'} |")
        if session_cost:
            L += ["", f"Estimated AI cost for this run: **${sum(session_cost.values()):.2f}** "
                  f"({len(session_cost)} Claude Code sessions, client-side estimate)."]
        L.append("")
    blocked = _load(cfg.out / "blocked.json")
    if blocked:
        L += ["## Blocked", "",
              f"**{blocked['unit']}** still failed after {blocked['attempts']} attempts. The attempts are on branch "
              f"`{blocked['branch']}`; the working branch was reset to `{blocked['reset_to']}` and the pipeline stopped.", ""]

    L += ["## Behaviour changes and decisions", ""]
    changes = dec.get("behaviour_changes") or []
    if not changes:
        L += ["No behaviour changes were found.", ""]
    else:
        L += ["| Field | Legacy | New | Decision | By |", "|---|---|---|---|---|"]
        for ch in changes:
            ex = ch["example"]
            L.append(f"| `{ch['field']}` | {ex['legacy']} | {ex['new']} | **{ch['decision']}** | {ch['decided_by']} |")
        L.append("")
        expl = "\n\n".join(e["text"] for e in dec.get("ai_explanations") or [])
        if expl:
            L += ["AI explanation shown to the reviewer at decision time:", "", *[f"> {ln}" if ln else ">" for ln in expl.splitlines()], ""]

    if cov:
        L += ["## Test coverage of the new backend", "",
              f"The API parity cases execute **{cov['percent']}%** of `modern/backend/app.py` "
              f"({cov['statements'] - len(cov['missing'])} of {cov['statements']} statements).", ""]
        if cov["missing"]:
            L += [f"Not exercised (lines): {', '.join(map(str, cov['missing']))}. Parity is only proven for code the tests run.", ""]

    L += ["## Follow-ups", ""]
    follow = []
    for ch in changes:
        if ch["decision"] == "keep-legacy":
            follow.append(f"`{ch['field']}` kept its Python 2 behaviour on purpose. If it was a bug, fix it in a separate, visible change.")
        if ch["decision"] == "accept-new":
            follow.append(f"`{ch['field']}` now behaves differently from the legacy app. Tell the API's consumers.")
    follow += [f"Unresolved `MODERNIZE-REVIEW` note at {r}." for r in review_left]
    if plan and not e2e["hybrid"]["passed"]:
        follow.append("Hybrid rollout not tried yet (`modernize bridge`).")
    follow.append("Retire the legacy Python 2.7 container once the new backend is live.")
    L += [f"- {f}" for f in follow] + [""]

    L += ["## Rollback", "",
          "- Backend and frontend live side by side (`legacy/` and `modern/`), so switching back is a routing change, not a redeploy of old code.",
          "- Every AI and codemod edit is its own commit (table above); revert any single step with `git revert <sha>`.", ""]

    out = cfg.migration / "REPORT.md"
    out.write_text("\n".join(L), encoding="utf-8")
    ok(f"Wrote {out.relative_to(root)}")
    return out
